### PR TITLE
Freeze all the things

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Benchmark with [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) is from one of my rails project.

Before

```
$ bundle exec derailed bundle:mem
TOP: 88.7383 MiB
  country_select: 29.918 MiB
    iso3166: 28.75 MiB <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      iso4217: 0.6953 MiB
        currencies/currency: 0.6445 MiB
    sort_alphabetical: 0.9258 MiB
      unicode_utils/general_category: 0.8477 MiB
        unicode_utils/gc: 0.8047 MiB
```

After

```
  country_select: 2.5352 MiB
    sort_alphabetical: 2.0469 MiB
      unicode_utils/general_category: 1.2617 MiB
        unicode_utils/gc: 1.2422 MiB
      unicode_utils/compatibility_decomposition: 0.7383 MiB
```

Saves about 28.75 MiB at require.

### CODE REVIEW

**Comment by schneems** [comment]
That's some great savings and a pretty minimal patch, great work :heart: any blockers to merging @vandrijevik ?

**Comment by vandrijevik** [comment]
No objections here, thank you for the contribution! Sorry I did not see it earlier, it just landed in my notifications.

**Comment by vandrijevik** [comment]
I will prepare a new release and do it tomorrow (Friday) – it is pretty late where I am. Thank you both!

**Comment by JuanitoFatas** [comment]
:+1: Thank you!

**Comment by vandrijevik** [comment]
@JuanitoFatas By the way, the gem in your benchmark is actually not this gem: `country_select` [depends on `countries`](https://github.com/stefanpenner/country_select/blob/master/country_select.gemspec#L28) which has a [`iso3166`](https://github.com/hexorx/countries/blob/master/lib/iso3166.rb) inside its `lib/`, so it is curious that you saw a difference in memory usage by patching this code.

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas By the way, the gem in your benchmark is actually not this gem: country_select depends on countries which has a iso3166 inside its lib/, so it is curious that you saw a difference in memory usage by patching this code.

:scream: let me double check, sorry!

**Comment by JuanitoFatas** [comment]
Sorry! I was wrong! I saw iso3166 using 28MB, so I forked this iso3166, add it to my Gemfile:

     gem 'iso3166', github: 'juanitofatas/iso3166', branch: 'feature/frozen'

And re-benchmark it was gone from the list make me thought that this pull request is legit...

My apologies! But this pull request is also legit, saves allocating `"UTF-8"` and `"ISO-8859-1"` 252+252=504 times and `";"` 250+250=500 times...

If you want to revert I'm ok! I'll make PR to countries gem, thank you so much!

**Comment by vandrijevik** [comment]
@JuanitoFatas No worries, thanks for looking into this and writing back! I already released `0.1.1`, so I’ll leave it as-is.

**Pull request merged**
